import type { MailMessage } from "./types";

export const demoMails: MailMessage[] = [
  { id: "demo-1", uid: 101, folder: "INBOX", senderName: "林晓 · 产品部", senderEmail: "xiaolin@example.com", recipients: ["me@example.com"], subject: "请确认 Q3 发布清单", receivedAt: "2026-08-28T08:42:00+08:00", bodyText: "你好，请在明天 10:30 前确认 Q3 发布清单，并回复风险项。\n\n附件中的版本说明供参考。", category: "待办", classificationReason: "关键词：请确认", isRead: false, reminderStatus: "none" },
  { id: "demo-2", uid: 102, folder: "INBOX", senderName: "课程助教", senderEmail: "ta@bnbu.edu.cn", recipients: ["student@mail.bnbu.edu.cn"], subject: "统计学作业提交提醒", receivedAt: "2026-08-28T07:20:00+08:00", bodyText: "本周课程作业请在周五 23:59 前提交。", category: "学业", classificationReason: "关键词：作业", isRead: false, reminderStatus: "none" },
  { id: "demo-3", uid: 103, folder: "INBOX", senderName: "学生事务处", senderEmail: "sao@bnbu.edu.cn", recipients: ["student@mail.bnbu.edu.cn"], subject: "新学期校园卡办理通知", receivedAt: "2026-08-27T16:05:00+08:00", bodyText: "校园卡集中办理安排已经发布，请按学院时间到场。", category: "校园事务", classificationReason: "关键词：校园卡", isRead: true, reminderStatus: "created" },
  { id: "demo-4", uid: 104, folder: "INBOX", senderName: "摄影社", senderEmail: "photo.club@mail.bnbu.edu.cn", recipients: ["student@mail.bnbu.edu.cn"], subject: "秋季摄影活动报名", receivedAt: "2026-08-27T11:30:00+08:00", bodyText: "社团秋季外拍活动开始报名，名额有限。", category: "社团活动", classificationReason: "关键词：社团", isRead: true, reminderStatus: "none" },
  { id: "demo-5", uid: 105, folder: "INBOX", senderName: "SGE WPEC", senderEmail: "jobs@example.com", recipients: ["student@mail.bnbu.edu.cn"], subject: "Recruitment: WPEC Experiential Arts Student Assistant", receivedAt: "2026-08-26T15:12:00+08:00", bodyText: "Dear students, we are recruiting student assistants for the WPEC Experiential Arts programme. Please review the position details and submit your application before Friday.", category: "实习", classificationReason: "关键词：recruitment", isRead: true, reminderStatus: "none" }
];
